---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
ATILDA JANE, you never look
At any toy or picture-book.
I show you pretty things in vain--
You must be blind, Matilda Jane!
 I ask you riddles, tell you tales,


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->Now close the windows and hush all the fields:    
If the trees must, let them silently toss;    
No bird is singing now, and if there is,    
Be it my loss.  
It will be long ere the marshes resume,  
 
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."   

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
A strong song tows  
us, long earsick.  
Blind, we follow  
rain slant, spray flick  
to fields we do not know.  
Night, float us.  
Offshore wind, shout,  
ask the sea  
what’s lost, what’s left,  
what horn sunk,  
what crown adrift.  
Where we are who knows  
of kings who sup  
while day fails? Who,  
swinging his axe  
to fell kings, guesses  
where we go?   